using System;

namespace ERC.Cli
{
    /// <summary>
    /// The settings a user changes with the global switches, for one debugging session.
    /// </summary>
    /// <remarks>
    /// Replaces a static mutable class. Those fields were written from x64dbg's
    /// command thread with no synchronisation and no way to observe them from a test,
    /// which is why none of the argument handling could be tested at all.
    ///
    /// Reset each time x64dbg restarts, matching the documented behaviour.
    /// </remarks>
    public sealed class SessionState
    {
        /// <summary>Exclude modules that opt in to ASLR from search results.</summary>
        public bool Aslr { get; set; }

        /// <summary>Exclude modules that use SafeSEH from search results.</summary>
        public bool SafeSeh { get; set; }

        /// <summary>Exclude modules that can be rebased from search results.</summary>
        public bool Rebase { get; set; }

        /// <summary>Exclude DEP-compatible modules from search results.</summary>
        public bool NxCompat { get; set; }

        /// <summary>Exclude operating system DLLs from search results.</summary>
        public bool OsDll { get; set; }

        /// <summary>Use the extended character set for patterns and FindNRP.</summary>
        public bool Extended { get; set; }

        /// <summary>Character encoding searches use for text.</summary>
        public SearchEncoding Encode { get; set; } = SearchEncoding.ASCII;

        /// <summary>
        /// Bytes that disqualify a pointer from search results, and are left out of
        /// generated byte arrays.
        /// </summary>
        public byte[] Bytes { get; set; } = new byte[0];

        /// <summary>
        /// Memory protection a pointer must have to appear in search results.
        /// </summary>
        public string Protection { get; set; } = "read,write";

        /// <summary>
        /// A copy, so handing the state to a command cannot let it change the session
        /// by accident.
        /// </summary>
        public SessionState Clone()
        {
            var copy = (SessionState)MemberwiseClone();
            copy.Bytes = (byte[])Bytes.Clone();
            return copy;
        }

        /// <summary>
        /// Returns the state to its defaults, as "ERC --reset" does.
        /// </summary>
        public void Reset()
        {
            Aslr = false;
            SafeSeh = false;
            Rebase = false;
            NxCompat = false;
            OsDll = false;
            Extended = false;
            Encode = SearchEncoding.ASCII;
            Bytes = new byte[0];
            Protection = "read,write";
        }
    }
}
